- README.md
The leading quote around the dependency version was in the wrong location.
> Update dependency block in README.md

- lib/adapters/adapter.ex
- lib/adapters/datadog.ex
- lib/adapters/helpers.ex
- lib/plug/start_trace.ex
- lib/spandex.ex
- test/plug/start_trace_test.exs
Adds support for distributed tracing using the `x-datadog-trace-id` and `x-datadog-parent-id` as discussed in https://github.com/zachdaniel/spandex/issues/6.
> Distributed Tracing

- README.md
Fixes the header names used in the distributed tracing in README.md.
(Aside from these ones being used in the code, they were also taken from https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#distributed-tracing)
> Fix header names in README distributed tracing section

- lib/adapters/datadog.ex
- test/plug/start_trace_test.exs
I made a boo-boo in the original distributed tracing; datadog expects the trace ID and parent span ID to be integers (i.e. not in string format). As headers are strings across the network, we need to parse 'em back out to integers. Have tested this now and am seeing lovely distributed traces.
> Parse datadog distributed headers properly

- .formatter.exs
- .travis.yml
- benchmarks/plugs.exs
- benchmarks/support/adapter.ex
- benchmarks/support/sender.ex
- benchmarks/support/tracer.ex
- lib/tracer.ex
- mix.exs
- mix.lock
This is an initial stab at adding [Benchee](https://github.com/PragTob/benchee) benchmarks for the `Spandex.Plug.*` modules to get a feel for how much performance impact there is when adding Spandex to a service. It is important to note that since the `BaselineRouter` doesn't really do anything, the `x slower` metrics are meaningless, so we should focus on the raw per-request timing increases due to adding tracing (in terms of how many microseconds is tracing adding to each request we process).
I wanted to get this in place so that I can work on an implementation for trace sampling (hence the stubbed-in `inputs` list) and validate that it alleviates the performance overhead of tracing, at least on average, when only sampling a small fraction of requests.
Feedback welcome!
Some initial …
> Add Benchee benchmarks for Plugs

- lib/spandex.ex
- test/span_test.exs
This should solve #55 and allow creating span based on logs.
> Stop overriding completion_time when finishing span

- lib/span.ex
This takes a different approach, to ensure that the create logic is always funneled through the update logic. Its a little bit more confusing, but ensures that the functionality between update and new are always aligned.
> Tweaking the dialyzer fixes for `Span.new()`

- .formatter.exs
- lib/adapter.ex
- lib/plug/add_context.ex
- lib/plug/end_trace.ex
- lib/plug/start_trace.ex
- lib/span.ex
- lib/spandex.ex
- lib/trace.ex
- lib/tracer.ex
- mix.exs
- test/plug/add_context_test.exs
- test/plug/end_trace_test.exs
- test/spandex_test.exs
When running `mix dialyzer`, I was getting the following errors:
```
lib/span.ex:87: Function new/1 has no local return
lib/span.ex:88: The call 'Elixir.Spandex.Span':update(#{'__struct__'=>'Elixir.Spandex.Span', 'completion_time'=>'nil', 'env'=>'nil', 'error'=>'nil', 'http'=>'nil', 'id'=>'nil', 'name'=>'nil', 'parent_id'=>'nil', 'private'=>'nil', 'resource'=>'nil', 'service'=>'nil', 'sql_query'=>'nil', 'start'=>'nil', 'tags'=>'nil', 'trace_id'=>'nil', 'type'=>'nil'},_opts@1::any(),#{'__struct__':='Elixir.Optimal
.Schema', 'annotations':=[], 'custom':=[], 'defaults':=[{'private',[]} | {'services',[]} | {'tags',[]},...], 'describe':=[], 'extra_keys?':='true', 'opts':=[atom(),...], 'required':=['env' | 'id' | 'name' | 'service' | 'start' | 'trace_id',...], 'types':=[{atom(),'any' | 'atom' | …
```
> Fix dialyzer issues and use :ok tuples when :error tuples are possible

- lib/tracer.ex
- test/configure_test.exs
Currently, even when `Tracer.configure(disabled?: true)` is called, the spandex is not disabled.
There is another issue that calls of `trace_start` and `span_start` after dynamic configuration of tracer  using `Tracer.configure(service: :app, adapter: ..., disabled?: true)` will cause exception like:
```
** (EXIT) an exception was raised:
** (ArgumentError) Opt Validation Error: service - is required, adapter - is required
(optimal) lib/optimal.ex:44: Optimal.validate!/2
(mikoto) lib/mikoto/tracer.ex:2: Mikoto.Tracer.config/2
(mikoto) lib/mikoto/tracer.ex:2: Mikoto.Tracer.start_span/2
```
This is because the option is not `Application.put_env` when `disabled?: true`.
This patch fixes the issue.
> Fix broken `Tracer.configure(disabled?: true)`

- README.md
- lib/spandex.ex
- lib/strategy.ex
- lib/strategy/pdict.ex
- lib/tracer.ex
- test/plug/add_context_test.exs
- test/plug/end_trace_test.exs
- test/spandex_test.exs
@GregMefford mentioned that a lot of the return types in the inner parts (and some of the public interface) were not conventional. This updates the ones from the strategy behaviour to follow that convention, and adapts much of the spandex code to handle that.
> standardize return types from strategies (and by proxy from Spandex)

- lib/span.ex
- lib/tracer.ex
When working on the `spandex_datadog` sender, I realized that we don't currently have a way to _not_ send the `env` with the spans. With Datadog, if you don't specify an `env` in the application like this, it will use the `env` configured in the trace collector agent. This PR makes it possible to do so, and I have another PR ready on the `spandex_dagtadog` repo that supports this from that end.
> Don't require that the env be specified

- lib/adapter.ex
- lib/plug/start_trace.ex
- lib/span.ex
- lib/span_context.ex
- lib/spandex.ex
- lib/trace.ex
- lib/tracer.ex
- test/spandex_test.exs
- test/support/adapter.ex
- test/support/sender.ex
- test/support/util.ex
Related to https://github.com/spandex-project/spandex_datadog/pull/3, this creates a new `Spandex.SpanContext` struct that we can use to control the API around distributed trace contexts.
Resolves #72
> Introduce SpanContext for distributed tracing

- CHANGELOG.md
- README.md
- lib/tracer.ex
- mix.exs
I've put together some release notes and updated the `README` to reflect recent changes.
I also noticed that we've deprecated an API in `Spandex`, but accidentally removed it entirely from `Tracer`, so I added it back in there and marked it deprecated for now.
> Prep for a 2.2.0 release

- README.md
Using `Mix.env/0` in the configuration example is likely to lead to issues when someone tries to use code like that in a release, as Mix is not intended (and basically does not work) in releases. This PR adds a warning and alternative option for the same config, but it may be preferable to remove the use of `Mix.env/0` entirely and use something else as an example.
Nice work!
> Add warning about use of Mix.env/0 to README

- CHANGELOG.md
- lib/adapter.ex
- lib/spandex.ex
- lib/tracer.ex
- test/spandex_test.exs
- test/support/adapter.ex
Adds APIs for `current_context` (to allow people to get access to a `SpanContext` based on the current span context) and `inject_context` to simplify adding distributed tracing headers to HTTP calls.
This somewhat-unfortunately also required an update to the `Adapter` behaviour, so I've also got a PR to `SpandexDatadog` queued up (https://github.com/spandex-project/spandex_datadog/pull/6).
> Add inject_context and current_context

- lib/plug/end_trace.ex
I got pretty confused when I kept getting a compile error telling me `tracer` was required, but I couldn't decipher it until I looked at the code for `EndTrace`. Since we have optimal and the schema here, lets add the free docs. 
/cc @zachdaniel @GregMefford @thebritican
> document the options for the end trace plug

- lib/spandex.ex
- lib/tracer.ex
- test/span_test.exs
We need to update the span according to any opts passed to `finish_span` and `finish_trace`.
> fix: update span on finish trace/update

- lib/spandex.ex
- test/spandex_test.exs
This addresses *some* but not all of the issues in #65. I'm still not sure how we should return from `start_trace` `start_span` `finish_trace` `finish_span` and the `continue_*` functions if given invalid updates. Its been discussed in slack, and we probably shouldn't just *skip* starting the span, and we also should raise an error. Likewise, returning `{:error, error}` but *still* starting the trace/span might be wrong. Really not sure of the best path forward there.
> fix: don't silence errors on span update calls

- lib/tracer.ex
Dialyzer complains about a type not being found when using
```elixir
use Spandex.Tracer, otp_app: :pg_payments
```
```
:0:unknown_type
Unknown type: Tracer.opts/0.
```
Fix the type
> Fix Tracer.opts/0 type

- lib/spandex.ex
- lib/tracer.ex
- test/decorators_test.exs
- test/spandex_test.exs
Does it make sense to log the `trace_id` in these cases as well? Thanks.
> Add missing trace_id to logger metadata

- lib/spandex.ex
- test/spandex_test.exs
Since this entry point can be called when a distributed trace is received from
another service, calling Logger.metadata in the same way it is called in
`start_trace/2` seems to cover that use-case (it should be idempotent, thus safe
if the same trace_id is already there from another local process).
However, I believe this may also fix an issue as a new span is created when
continuing a trace, which that should be updated in logs from this moment on.
Do you think this may be helpful?
> Update logger metadata when continue trace is called

- lib/adapter.ex
- lib/spandex.ex
- test/spandex_test.exs
- test/support/adapter.ex
This change allows headers to be specified in `Spandex.distributed_context/2` as an alternative to `Plug.Conn`. This is more compatible with the current signature of `Spandex.inject_context/3` and allows Spandex to be used to extract trace information from connections that may not be relying on Plug e.g. GRPC.
Fixes #112
Haven't been using Elixir for too long, so let me know if there is anything funky going on that I should be doing differently.
PR for spandex_datadog will follow once this one gets sorted out.
> feat!: allow headers to be passed into `Spandex.distributed_context/2`

- lib/tracer.ex
As of 43c256b6926a065345ed38115ca1ba6ca0998583 the sender was no longer correctly being configured for the tracer. This causes the tests in spandex_datadog to fail as the default adapter will always be used.
This change re-adds the ability to configure the sender on the tracer.
> Correctly configure sender in tracer

- lib/spandex.ex
When errors like `Tried to start a trace over top of another trace` happen, it's not obvious from where they originate. So I added a name to log messages
> fix: add a name to failed traces

- lib/span.ex
- lib/tracer.ex
- mix.exs
Elixir 1.11 generates deprecation warnings from the use of `System.stacktrace/0` in the `trace` macro.
Eg:
```
warning: System.stacktrace/0 is deprecated, use __STACKTRACE__ instead
lib/services/search/elasticsearch.ex:195
```
Since the warning is reported as being in my application code (rather than the library), the build fails when compiling with the `--warnings-as-errors` flag.
This PR changes the implementation to use `__STACKTRACE__` instead, which should be equivalent.
I've also updated the minimum elixir version to [1.7](https://github.com/elixir-lang/elixir/releases/tag/v1.7.0), since `__STACKTRACE__` isn't supported in lower versions.
> Replace System.stacktrace with __STACKTRACE__

- .circleci/config.yml
- mix.exs
There's an inconsistency in formatting of `mix.exs` - it got there because 1) we're not running `mix format --check-formatted` in CI, 2) we're not allowing CI checks to run on forks. This PR is fixing the former (and the formatting error itself). Could anyone help with the latter? To allow builds on PRs from forks you need to enable "Build forked pull requests" under the Advanced tab in project settings in CircleCI.
> Run mix format in CI

- lib/spandex.ex
- lib/tracer.ex
While updating one of our apps from Spandex 2.4.4 to 3.0.3, we hit an issue where it was crashing at runtime where it hadn't before. We traced it down to these new Spandex error logs that weren't using `inspect` and were failing to encode a keyword list of opts as a string, because at some earlier point, we had moved from using Decorators to using the Tracer macros and made a mistake in the conversion:
From:
```
@decorate trace(name: "somename", service: "someservice")
def some_function do
:noop
end
```
To:
```
def some_function do
Tracer.trace(name: "somename", service: "someservice") do
:noop
end
end
```
Instead of:
```
def some_function do
Tracer.trace("somename", service: "someservice") do
:noop
end
end
```
The bug here was subtle: rather than passing in a name and opts, we're …
> Guard clauses for trace and span macros

- .github/FUNDING.yml
I set up a GitHub sponsorship profile the other day and I saw that you also have one @zachdaniel, so I figure it doesn't hurt to make that easier for people to find. I believe this will cause our sponsorship details to be included in `mix hex.sponsor` output because we have a `github` link in our `mix.exs`, but we'll see if that's really how it works.
> Set up sponsorship links
